"use strict";

const wordsEasy = [
    { id: 1, word: "chocolate" },
    { id: 2, word: "banana" },
    { id: 3, word: "apple" },
    { id: 4, word: "Ball" },
    { id: 5, word: "Egg" },
    { id: 6, word: "Game" },
    { id: 7, word: "Car" },
    { id: 8, word: "Water" },
    { id: 9, word: "House" },
    { id: 10, word: "Day" },
    { id: 11, word: "Hello" },
    { id: 12, word: "Box" },
    { id: 13, word: "Boy" },
    { id: 14, word: "Milk" },
    { id: 15, word: "Cat" },
    { id: 16, word: "Sun" },
    { id: 17, word: "Old" },
    { id: 18, word: "Park" },
    { id: 19, word: "Hi" },
    { id: 20, word: "Bye" },
  ];
  
  const wordsMedium = [
    { id: 21, word: "library" },
    { id: 22, word: "Money" },
    { id: 23, word: "Morning" },
    { id: 24, word: "Cloud" },
    { id: 25, word: "Watch" },
    { id: 26, word: "Bear" },
    { id: 27, word: "View" },
    { id: 28, word: "Friendly" },
    { id: 29, word: "Friend" },
    { id: 30, word: "Allow" },
    { id: 31, word: "Difference" },
    { id: 32, word: "Expert" },
    { id: 33, word: "Prince" },
    { id: 34, word: "Damage" },
    { id: 35, word: "Success" },
    { id: 36, word: "Sletter" },
    { id: 37, word: "Benefit" },
    { id: 38, word: "Street" },
    { id: 39, word: "Wind" },
    { id: 40, word: "Garden" },
  ];
  
  const wordsHard = [
    { id: 41, word: "Blinker" },
    { id: 42, word: "Foreign" },
    { id: 43, word: "Arctic" },
    { id: 44, word: "Assume" },
    { id: 45, word: "Conceptions" },
    { id: 46, word: "Create" },
    { id: 47, word: "Definition" },
    { id: 48, word: "Derive" },
    { id: 49, word: "Dissimilarity" },
    { id: 50, word: "Identify" },
    { id: 51, word: "Economy" },
    { id: 52, word: "Distribute" },
    { id: 53, word: "Establish" },
    { id: 54, word: "Indicate" },
    { id: 55, word: "Heavy" },
    { id: 56, word: "Forever" },
    { id: 57, word: "Compact" },
    { id: 58, word: "Stranger" },
    { id: 59, word: "Crazy" },
    { id: 60, word: "Silly" },
  ];
  
  ///// Translated to Uzbek //////
  const translateEasyWord = [
    { id: 1, word: "Shokolad" },
    { id: 2, word: "banan" },
    { id: 3, word: "Olma" },
    { id: 4, word: "to'p" },
    { id: 5, word: "tuxum" },
    { id: 6, word: "O'yin" },
    { id: 7, word: "Mashina" },
    { id: 8, word: "Suv" },
    { id: 9, word: "Uy" },
    { id: 10, word: "Kun" },
    { id: 11, word: "Salom" },
    { id: 12, word: "Quti" },
    { id: 13, word: "Bola" },
    { id: 14, word: "Sut" },
    { id: 15, word: "Mushuk" },
    { id: 16, word: "Quyosh" },
    { id: 17, word: "Eski" },
    { id: 18, word: "Park" },
    { id: 19, word: "Salom(do'stona)" },
    { id: 20, word: "Hayr" },
  ];
  
  const translateMediumWord = [
      { id: 21, word: "Kutubxona" },
      { id: 22, word: "Pul" },
      { id: 23, word: "Ertalab" },
      { id: 24, word: "Bulut" },
      { id: 25, word: "Tomosha qilmoq" },
      { id: 26, word: "Ayiq" },
      { id: 27, word: "Korinish" },
      { id: 28, word: "Do'stona" },
      { id: 29, word: "Do'st" },
      { id: 30, word: "Ruxsat berish" },
      { id: 31, word: "Farq" },
      { id: 32, word: "Mutaxasis" },
      { id: 33, word: "Shahzoda" },
      { id: 34, word: "Zarar" },
      { id: 35, word: "Muvaffaqiyat" },
      { id: 36, word: "Yaltiroq" },
      { id: 37, word: "Foydali" },
      { id: 38, word: "Ko'cha" },
      { id: 39, word: "Shamol" },
      { id: 40, word: "Bog\'" },
  ];
  
  const translateHardWord = [
      { id: 41, word: "Miltillash" },
      { id: 42, word: "Xorijiy" },
      { id: 43, word: "Arktika" },
      { id: 44, word: "Faraz qilish" },
      { id: 45, word: "Tushunchalar" },
      { id: 46, word: "Yaratmoq" },
      { id: 47, word: "Ta\'rif" },
      { id: 48, word: "Hosil qilmoq" },
      { id: 49, word: "O\'xshashlik" },
      { id: 50, word: "Aniqlash" },
      { id: 51, word: "Iqtisodiyot" },
      { id: 52, word: "Tarqatish" },
      { id: 53, word: "Tashkil etmoq" },
      { id: 54, word: "Ko\'rsatish" },
      { id: 55, word: "Og\'ir" },
      { id: 56, word: "Abadiy" },
      { id: 57, word: "Ixcham" },
      { id: 58, word: "Begona" },
      { id: 59, word: "Aqildan ozish" },
      { id: 60, word: "Ahmoq" },
    ];